// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistance.Sqlite;

namespace Persistance.Sqlite.Migrations
{
    [DbContext(typeof(BalanceContext))]
    [Migration("20190209211927_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028");

            modelBuilder.Entity("Storage.Sqlite.Models.BalanceSheet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("BalanceSheets");
                });

            modelBuilder.Entity("Storage.Sqlite.Models.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Amount");

                    b.Property<Guid?>("BalanceSheetId");

                    b.Property<string>("Description");

                    b.Property<string>("LinkedFiles");

                    b.HasKey("Id");

                    b.HasIndex("BalanceSheetId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("Storage.Sqlite.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BalanceSheetId");

                    b.Property<string>("FirstName");

                    b.Property<Guid?>("PostId");

                    b.HasKey("Id");

                    b.HasIndex("BalanceSheetId");

                    b.HasIndex("PostId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Storage.Sqlite.Models.Post", b =>
                {
                    b.HasOne("Storage.Sqlite.Models.BalanceSheet")
                        .WithMany("Posts")
                        .HasForeignKey("BalanceSheetId");
                });

            modelBuilder.Entity("Storage.Sqlite.Models.User", b =>
                {
                    b.HasOne("Storage.Sqlite.Models.BalanceSheet")
                        .WithMany("Users")
                        .HasForeignKey("BalanceSheetId");

                    b.HasOne("Storage.Sqlite.Models.Post")
                        .WithMany("CreatingUser")
                        .HasForeignKey("PostId");
                });
#pragma warning restore 612, 618
        }
    }
}
