// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistance.Sqlite;

namespace Persistance.Sqlite.Migrations
{
    [DbContext(typeof(BalanceContext))]
    partial class BalanceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028");

            modelBuilder.Entity("Persistance.Sqlite.Models.BalanceSheet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("Slug");

                    b.HasKey("Id");

                    b.ToTable("BalanceSheets");
                });

            modelBuilder.Entity("Persistance.Sqlite.Models.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Amount");

                    b.Property<Guid?>("BalanceSheetId");

                    b.Property<DateTime>("CreateDate");

                    b.Property<string>("Description");

                    b.Property<DateTime>("EditDate");

                    b.Property<string>("ImgLocation");

                    b.Property<string>("LinkedFiles");

                    b.Property<Guid?>("OwnerId");

                    b.HasKey("Id");

                    b.HasIndex("BalanceSheetId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("Persistance.Sqlite.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BalanceSheetId");

                    b.Property<string>("FirstName");

                    b.HasKey("Id");

                    b.HasIndex("BalanceSheetId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Persistance.Sqlite.Models.Post", b =>
                {
                    b.HasOne("Persistance.Sqlite.Models.BalanceSheet")
                        .WithMany("Posts")
                        .HasForeignKey("BalanceSheetId");

                    b.HasOne("Persistance.Sqlite.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId");
                });

            modelBuilder.Entity("Persistance.Sqlite.Models.User", b =>
                {
                    b.HasOne("Persistance.Sqlite.Models.BalanceSheet")
                        .WithMany("Users")
                        .HasForeignKey("BalanceSheetId");
                });
#pragma warning restore 612, 618
        }
    }
}
